# -----------------------------------------------------------------------------
#
# This file is part of the xPack project (http://xpack.github.io).
# Copyright (c) 2025 Liviu Ionescu. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose is hereby granted, under the terms of the MIT license.
#
# If a copy of the license was not distributed with this file, it can
# be obtained from https://opensource.org/licenses/MIT.
#
# -----------------------------------------------------------------------------

  name: 'Test SourceForge downloads'

  on:
    schedule:
      - cron: '1 13 * * 6' # every Saturday
    workflow_dispatch:

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: xpack-dev-tools/xbb-helper-xpack
            ref: 'xpack-development'

        - name: Show environment
          run: |
            ls -lLA
            env | sort | grep -E '^[^ \t]+='

        - name: Run test
          run: |
            #!/usr/bin/env bash
            set -e

            # The script is in the xbb-helper-xpack repo.
            source maintenance-scripts/download-sourceforge-source.sh

            date

            # https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/tags
            # https://sourceforge.net/projects/riscv-none-elf-gcc-xpack/files/
            name="riscv-none-elf-gcc"
            # threshold=100
            threshold=0 # (100%)

            # 2025
            platforms="win32-x64,linux-x64,linux-arm64,darwin-x64,darwin-arm64"
            download_sourceforge "${name}" "12.5.0-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "13.4.0-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "14.3.0-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "15.2.0-1" ${threshold} "${platforms}"

            # 2024-2022
            platforms="win32-x64,linux-x64,linux-arm64,linux-arm,darwin-x64,darwin-arm64"

            download_sourceforge "${name}" "11.5.0-2" ${threshold} "${platforms}"
            download_sourceforge "${name}" "12.4.0-2" ${threshold} "${platforms}"
            download_sourceforge "${name}" "13.3.0-2" ${threshold} "${platforms}"
            download_sourceforge "${name}" "14.2.0-3" ${threshold} "${platforms}"
            # download_sourceforge "${name}" "14.2.0-2" ${threshold} "${platforms}" DELETED

            download_sourceforge "${name}" "11.5.0-2" ${threshold} "${platforms}"
            download_sourceforge "${name}" "12.4.0-2" ${threshold} "${platforms}"
            # download_sourceforge "${name}" "12.4.0-1" ${threshold} "${platforms}" DELETED
            download_sourceforge "${name}" "13.3.0-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "14.1.0-1" ${threshold} "${platforms}"

            download_sourceforge "${name}" "13.2.0-2" ${threshold} "${platforms}"
            download_sourceforge "${name}" "12.3.0-2" ${threshold} "${platforms}"
            download_sourceforge "${name}" "11.3.0-1" ${threshold} "${platforms}"
